use_frameworks!

platform :ios, '10.0'

target 'IntrfaxeWRTC_Example' do
  pod 'IntrfaxeWRTC', :path => '../'
  pod 'SnapKit', '~> 5.0.0'

  target 'IntrfaxeWRTC_Tests' do
    inherit! :search_paths

    
  end
end
